### ISSUE TITLE
"Make CTRL+Backspace and CTRL+Delete work in all textboxes" doesn't always work

### ISSUE THREAD

**Issue by dnbrv** [7plus/7plus#392]
<b>Is it reproducible?</b>
Not really. Happens occasionally.

<b>What is the expected output? What do you see instead?</b>
CTRL+Backspace is supposed to delete the entire word but only the first character is deleted.

<b>What version of the product are you using (Binary/Source/32/64bit)? On what</b>
<b>operating system (XP,Vista,7,32/64bit)?</b>
2.5.0 and 2.6.0 on Win7 Ultimate SP1 x64

Imported from Google Code [Issue 392](http://code.google.com/p/7plus/issues/detail?id=392)
Posted by denbara... on: 2012-08-14T20:36:47.000Z
Closed On:

**Comment by Akamaru217** [comment]
unsubscribe
________________________________
