### ISSUE TITLE
Help Please, I want it on my windows 8.1

### ISSUE THREAD

**Issue by X18** [7plus/7plus#421]
please make it compatible with windows 8.1

**Comment by dogshed** [comment]
First I couldn't find any installation instructions.
I created a directory in Program Files and put all the files there and then ran the 7plus.exe file.
It gave some kind of nasty error. I clicked OK. It gave another error. I clicked OK.
It then seemed like it was starting to install and froze up and I couldn't use my mouse.
I did control-alt-delete and used my touch screen to get the task manager.
I had to tap and wait and tap and wait to finally get it to die.

**Comment by lipkau** [comment]
7plus doesn't require an installation. You just run it from any folder.
By default 7plus tries to run as administrator. But if you place the files in program files, you **have to** run it as admin.

Regarding the error, could you please provide more detailed information? Preferably a screenshot?
