### ISSUE TITLE
Outlook 2010 pasting explorer path as clip.txt (not text)

### ISSUE THREAD

**Issue by sorashadow** [7plus/7plus#423]
Hello there.

I was trying to copy a path from explorer bar into Outlook compose window, but everytime I try to do so, it pastes the text as an archive, annexing it to the message.

I tried to remove Outlook windows from the handlers (_OUTLOOK.EXE_, _rctrl_renwnd32_, _ahk_class rctrl_renwnd32_), and even tried to manually remove it from the code of _clipboard.ahk_, but with no success.

Could you help me with a workaround? For now, the only thing I can do is use another AHK script of mine to convert it to pure text (`ClipBoard = %ClipBoard%`) and then paste it.

**Comment by ChrisS85** [comment]
I think it may be necessary to replace the clipboard temporarily in outlook by removing the entry related to the file used for pasting files in Explorer. It should be possible to restore the entry once Outlook isn't active anymore. Can't tell much more right now without digging in the code (not much time right now unfortunately).

**Comment by sorashadow** [comment]
I know you don't have much time, but is there any function (or source file) I can lookup, to try and modify?

**Comment by lipkau** [comment]
I don't feel like your solution is good enough.
Selecting a file in the explorer and hitting **alt + c** will copy the file name into the clipboard. _(withouth entring the renaming mode)_
However it will still paste the clip.txt into a html editor (Outlook, Word, etc).

I believe this check:
```if (WinActive("ahk_group ExplorerGroup") || WinActive("ahk_group DesktopGroup")|| IsDialog())```
in `OnClipboardChange()` should be removed.
It should not be the logic whilst copying that determins if a file will be written (or pasted) but the logic when pasting.

However I will align this with Chris before continuing with this.

**Comment by sorashadow** [comment]
No problems, there... Like I said, that was a _palliative_ solution; working for me, for now. I agree with you that it's not good enough; I didn't test it with all the options, and that was just a workaround.

I don't use many default actions / shortcuts, and that's why I didn't see that problem... Thanks for observing that ^_^
