### ISSUE TITLE
www.sevenplus.co: "Website Expired"

### ISSUE THREAD

**Issue by koppor** [7plus/7plus#425]
When opening http://www.sevenplus.co/ the text "Website Expired" appears.

**Comment by lipkau** [comment]
Thank you for raising this issue. we are working on it.

**Comment by Punknoodles** [comment]
Works for me.

**Comment by koppor** [comment]
![grabbed_20161128-223835](https://cloud.githubusercontent.com/assets/1366654/20687094/6a3f1a10-b5bb-11e6-8d47-69055a840d1d.png)
