### ISSUE TITLE
Slide Windows Portable

### ISSUE THREAD

**Issue by lucfig** [7plus/7plus#428]
Hi,

I am looking like cray for a way to implement Slide Windows into my work computer. I don't have admin access, o I cant install .Net framework.

Is it possible to have the Slide Windows script as standalone without all 7plus features?

Does anyones has an alternative for that?

Thanks and regards,

**Comment by ChrisS85** [comment]
I'm not sure about this as I haven't worked on that code for quite a few years. I think one would need to clarify if any event handlers are used that require admin permissions.

I think this feature only needs to access mouse position, screen size and listen to window (de)activations, all of which should be possible with standard AutoHotkey functionalities if I recall correctly. Apart from this it would be necessary to separate this feature from the rest of 7plus which obviously requires AutoHotkey proogramming knowledge.

**Comment by lucfig** [comment]
Thanks Chris.

Currently your code is indeed beyond my AHK knowledge, but I'm trying to separate it. 

Best regards.

**Comment by ChrisS85** [comment]
You will probably want to take a look at SlideWindows.ahk, AutoExecute.ahk, MessageHooks.ahk Actions/SlideWindowsOut.ahk and MiscFunctions.ahk. There might also be some dependencies with the settings and program exit.

Basically:
- Register all required event hooks and message handlers and call SlideWindows handlers like in 7plus.
- Trigger SlideWindowsOut action with your desired hotkeys
- Remove all dependencies on settings and possibly hard code them, read them from a config file, or similar.

As far as I can tell it should be working without admin permissions but don't take my word for it.
